# site settings
title: Sahil Dave
email: sahildave1991@gmail.com
description: Design + Dev + Create
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sahildave.xyz" # the base hostname & protocol for your site
city: Bangalore
state: KA
country: India

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
github_url: https://github.com/sahildave/
linkedin_url: https://www.linkedin.com/in/sahildave1991/
twitter_url: https://twitter.com/sahildave1991
cv_url:

# build settings
markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  style: compressed