# site settings
title: Sahil Dave
email: sahildave1991@gmail.com
description: Design + Dev + Create
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sahildave.xyz" # the base hostname & protocol for your site
city: Bangalore
state: KA
country: India
image: /assets/images/banner.jpg

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
github_url: https://github.com/sahildave/
linkedin_url: https://www.linkedin.com/in/sahildave1991/
twitter_url: https://twitter.com/sahildave1991
dribbble_url: https://dribbble.com/sahildave
behance_url: https://www.behance.net/sahildave
social:
  name: Sahil
  links:
    - https://twitter.com/sahildave1991
    - https://dribbble.com/sahildave
    - https://www.linkedin.com/in/sahildave1991/
    - https://www.behance.net/sahildave
    - https://github.com/sahildave/ 
author:
  twitter: sahildave1991

# build settings
markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-seo-tag