#
# Jekyll basic configurations
#

source:         _app
destination:    _site
permalink:      /:title.html
markdown:       kramdown
highlighter:    rouge
include:        ["_pages"]
exclude:        ["_pages/themes"]

#
# Jekyll serve settings
#

port:           4321

#
# Jekyll build settings
#

future:         false

#
# Markdown settings
#

kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  syntax_highlighter_opts:
    css_class:               "highlight"
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"

#
# Jekyll plugins
#

plugins:
  - jekyll-last-modified-at
  - match_regex
  - jekyll-seo-tag


#
# Almace Scaffolding settings
#

# Development mode
#
# Development mode is disabled on production build by default, we've enabled it
# in `_config.dev.yml` for local development, so most of the time you don't
# need to change it.
#
# Default:      false
dev:            false

# Site name
name:           Sahil Dave

# Site short name
name_short:     Sahil Dave

# Site description
description:    Sahil Dave's Portfolio

# Base URL
baseurl:        ""

# CSS path used in templates
assets:         /assets

# CDN location for development
file:           ""

# Feed URL
feed:           /feed.xml

# Site full URL
url:            https://www.sahildave.com

# Colors
#
# Used by Safari mask-icon, Chrome Web App theme color
colors:
  theme:        "#62E6AC"
  background:   "#ffffff"

# Service Worker Precache
service_worker:
  enabled:      true
  max_size:     120000
  files:
    - "**/*.{css,html,jpg,gif,png,svg,woff,woff2}"
    - "**/js/**.js"

# Google Analytics tracking code
google_analytics:
  enabled:      true
  id:           UA-56407221-3
  url:          https://www.googletagmanager.com/gtag/js


# SEO Plugin
title: Sahil Dave | Product Designer
logo: ./logo.png

# Site Twitter account handle
twitter:        sahildave1991

# social settings
github_url: https://github.com/sahildave/
linkedin_url: https://www.linkedin.com/in/sahildave1991/
twitter_url: https://twitter.com/sahildave1991
dribbble_url: https://dribbble.com/sahildave
behance_url: https://www.behance.net/sahildave
mail_url: mailto:sahildave1991@gmail.com
social:
  name: Sahil
  links:
    - https://twitter.com/sahildave1991
    - https://dribbble.com/sahildave
    - https://www.linkedin.com/in/sahildave1991/
    - https://www.behance.net/sahildave
    - https://github.com/sahildave/ 


# Twitter Cards large images
#
# Use summary card with large image for Twitter Cards, require theme support
#
# Default:      true
tc_large_image: true

# Force UTF-8 encoding
#
# Enable this will simply add <meta charset="utf-8"> to the head of your pages
#
# Default:      false
force_utf_8:    false

# Link blog
#
# Enable this settings to make your feed Daring Fireball-like link blog (This
# basically change your <link> value to external link you defined in your posts)
#
# Default:      false
link_blog:      false

# Excerpts for RSS
#
# Change the value to true to use post excerpt for RSS feeds
#
# Default:      false
rss_excerpt:    false

# Generator credits
#
# Show or hide generator credits, require theme support
#
# Default:      true
credits:        true

# Custom records in robots.txt
#
# For example:
# robots:
#   - "User-agent: *"
#   - "Disallow: /ajax/"
#   - "Disallow: /@async"
#   - "Disallow: /log/"
#
# Default:      "User-agent: *"
robots:         "User-agent: *"
