source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'jekyll-seo-tag'
end

group :development do
  gem 'jekyll', '3.7.0'
  gem 'jekyll-last-modified-at'
  gem 'match_regex'
  gem 'stringex'
end